### ISSUE TITLE
dragging item to group with no draggable rows.

### ISSUE THREAD

**Issue by colinbes** [kutlugsahin/vue-smooth-dnd#103]
Not sure if the problem is related to issue #49 or not but if not then how does one drop an item into an empty list? Should this work or is there an issue.

Is it related to #49 in that dropping below last item doesn't work?

**Comment by davestewart** [comment]
I generally set a min-height and bottom-padding on the container class and it solves it:

```css
.win-item .smooth-dnd-container {
    padding-bottom: 20px;
    min-height: 50px;
}
```
