### ISSUE TITLE
Drop-placeholder doesn't seem to apply

### ISSUE THREAD

**Issue by laurent-brisbois** [kutlugsahin/vue-smooth-dnd#156]
Hi !

I'm using vue-smooth-dnd to build a kanban board and it's working well so far.
The only thing that isn't working for me is the `:drop-placeholder`.

Actually I'm trying to mimic the [cards page](https://kutlugsahin.github.io/vue-smooth-dnd/#/cards) of the demo.

```
"vue": "^2.6.10",
"vue-smooth-dnd": "^0.8.1",
"vuetify": "^2.2.21",
```

```html
      <Container
        group-name="tickets"
        @drop="(event) => onTicketDrop(stage, event)"
        :get-child-payload="getTicketPayload(stage)"
        drag-class="ticket-ghost"
        drop-class="ticket-ghost-drop"
        :drop-placeholder="dropPlaceholderOptions">
        <Draggable
          v-for="ticket in stage.ticketIds"
          :key="ticket.id">
          <v-card outlined class="ticket-card">
            <v-card-title class="subtitle-2">{{ ticket.name }}</v-card-title>
          </v-card>
        </Draggable>
      </Container>
```

```js
  data () {
    return {
      dropPlaceholderOptions: {
        className: 'drop-preview',
        animationDuration: '150',
        showOnTop: true
      }
    }
  }
```

```css
  .ticket-ghost {
    cursor: grabbing;
    transition: transform 0.18s ease;
    transform: rotateZ(5deg);
  }
  .ticket-ghost-drop {
    transition: transform 0.18s ease-in-out;
    transform: rotateZ(0deg);
  }
  .drop-preview {
    background-color: rgba(150, 150, 200, 0.1);
    border: 1px dashed red;
    margin: 5px;
  }
```

What am I doing wrong ?

You can see below that there is no zone with red border that appears :

![image](https://user-images.githubusercontent.com/48165976/85691846-27307d80-b6d5-11ea-9e05-58b2d116cdc0.png)

**Comment by sheibeck** [comment]
I'm having this same issue. I can't get a drop-placeholder class to apply either. Any pointers would be appreciated.

```
<Container id="drag-container" style="min-height:150px;"
        group-name="zone" 
        :get-ghost-parent="getGhostParent" 
        :get-child-payload="getChildPayload"
        @drag-enter="onDragEnter"
        drag-handle-selector=".objectHandle"  
        @drop="onZoneDrop(commonSvc.GetId(zone.id), $event)"
        drag-class="card-ghost" 
        drop-class="card-ghost-drop" 
        :drop-placeholder="dropPlaceholderOptions">            
        <Draggable style="min-height:150px;" v-for="item in zone.sceneobjects" :key="item.id">
          <sceneobject :objectdata="item" />
        </Draggable>
      </Container>      
```
```
 dropPlaceholderOptions: {
        className: 'drop-preview',
        animationDuration: '150',
        showOnTop: true
      },
```

```
.drop-preview {
    background-color: rgba(150, 150, 200, 0.1) !important;
    border: 1px dashed red !important;
    margin: 5px !important;
    z-index: 88888;
    min-height: 200px;
  }  
```

**Comment by laurent-brisbois** [comment]
@sheibeck 
Waiting for an answer here.

**Comment by laurent-brisbois** [comment]
@sheibeck 
Try with just `:drop-placeholder="true"` and the basic drop-placeholder (I guess default one) will appear.

Then I found out the CSS class to which default style is applied, which is `.smooth-dnd-drop-preview-default-class` but I can't apply other style to it except directly through the developer tools in the browser.

Any advice to force the style ?

I tried with CSS like this :

```css
.smooth-dnd-drop-preview-default-class {
  background-color: rgba(150, 150, 200, 0.1);
  border: 1px dashed red;
}
```
and even with `!important` keyword but it doesn't apply.
I also tried `>` operator to go from element to element with known classes that I found while inspecting the drop-preview element in the developer tools but nothing.
