### ISSUE TITLE
Is there a way to make containers with same group the same height?

### ISSUE THREAD

**Issue by LisaMaagdenberg** [kutlugsahin/vue-smooth-dnd#20]
I am working on an application where it is needed to drag orders from one column to the other. If one column is very large and the target column is almost empty, the user will have to drag the order to the top of the screen before dropping. If the target column is empty, it is very hard to "find" the container (find the place where to drop, so the onDrop function will be called).

Is there a way to make all the columns equal in height? I didn't see it in the demo.

**Comment by TitanFighter** [comment]
@LisaMaagdenberg Hi!. Maybe I do not understand something, but it seems your problem can be solved by using js. You need to find the height of the 1st column and then apply the same height to the second column.

**Comment by kutlugsahin** [comment]
Hi @LisaMaagdenberg 
One solution is like @TitanFighter said you can arrange height of columns by javascript after each drop.
You can also achieve this by overriding css classes of containers and draggables. For card board page in the demo app I added these classes to make them all equal height.

```css
.smooth-dnd-container.horizontal {
  display: flex;
}

.smooth-dnd-container.horizontal .smooth-dnd-draggable-wrapper {
  height: auto;
}

.card-container {
  height: 100%;
}

.card-container .smooth-dnd-container {
  height: 100%;
}
```
